# pull official base image
FROM python:3.9-bookworm
			
# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DPI_DEBUG_LEVEL 64
ENV ARCHFLAGS -arch x86_64




# install psycopg2 dependencies
#RUN apk update \
#    && apk add postgresql-dev gcc python3-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN echo $teste

# copy project
COPY . .

# Install OC 
RUN tar -xvf oc/openshift-client-linux-4.5.0-0.okd-2020-07-14-153706-ga.tar.gz
RUN ./oc version

RUN python3 src/main.py $test_mode
