# pull official base image
FROM python:3.9-bookworm
			
# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DPI_DEBUG_LEVEL 64
ENV ARCHFLAGS -arch x86_64

#Install OC to expose Openshift Postgres instance port
RUN wget https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-07-14-153706-ga/openshift-client-linux-4.5.0-0.okd-2020-07-14-153706-ga.tar.gz
RUN mkdir oci
RUN mv openshift-client-linux-4.5.0-0.okd-2020-07-14-153706-ga.tar.gz oci
RUN cd oci
RUN tar -xvf openshift-client-linux-4.5.0-0.okd-2020-07-14-153706-ga.tar.gz
RUN oc version

# install psycopg2 dependencies
#RUN apk update \
#    && apk add postgresql-dev gcc python3-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN echo $teste

# copy project
COPY . .
RUN python3 src/main.py $test_mode
