# pull official base image
#FROM registry.access.redhat.com/ubi8/python-39
FROM redhat/ubi8

# Main user
USER 0

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DPI_DEBUG_LEVEL 64
ENV ARCHFLAGS -arch x86_64

#Verify RUNnable apps
RUN compgen -ac
#RUN yum module install python39/build
RUN sudo dnf install python38
RUN sudo dnf install pip
RUN whereis python
RUN whereis pip

# install psycopg2 dependencies
#RUN apk update \
#    && apk add postgresql-dev gcc python3-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN echo $teste

# copy project
COPY . .
RUN python3 src/main.py $test_mode
